def show():
    print("     Entered Lilygo Keys    Results")
    print("     -------------------    -------")
    print("              _-               =")
    print("              (+               [")
    print("              +)               ]")
    print("              (-               <")
    print("              -)               >")
    print("              _#               ^")
    print("              _/               \\")
    print("              -/               %")
    print("              _!               &")
    print(" Speaker Key (left of enter)   $")
    print(" Track ball up                 up arrow")
    print(" Track ball down               down arrow")
    print(" Track ball left               left arrow")
    print(" Track ball right              right arrow")


show()
print('To re-display keys from repl type "keys.show()"')